#!/usr/bin/env bash
# This file is part of the Volta Project.
#
# Copyright (c) 2018 - 2019 AzuyaLabs
#
# License AGPL-3.0
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
#
# @author Sacha Telgenhof <me at sachatelgenhof dot com>

# VoltaPi generation script
# Shell script that runs in a Raspbian chroot to create the VoltaPi distro.

# Source error handling, leave this in place
set -x
set -e

export LC_ALL=C

source /common.sh
install_cleanup_trap

unpack /filesystem/home/$VOLTAPI_OS_USER /home/$VOLTAPI_OS_USER $VOLTAPI_OS_USER
unpack /filesystem/home/root /root root
unpack /filesystem/boot /boot

# Update OS
apt-get update
apt-get -y upgrade
apt install -y openssh-server net-tools nginx git apt-transport-https lsb-release zip curl dirmngr sudo

# Configuration
usermod -aG www-data $VOLTAPI_OS_USER
usermod -aG sudo $VOLTAPI_OS_USER

# Install PHP (and related)
wget -O /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg
echo "deb https://packages.sury.org/php/ $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/php7.3.list
apt-get update
apt-get install -y php7.3-cli php7.3-fpm php7.3-intl php7.3-json php7.3-mbstring php7.3-xml php7.3-curl php7.3-bcmath php7.3-zip php7.3-sqlite

curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/local/bin --filename=composer

# Install and configure Volta
echo "--- Installing Volta"
git clone -u pi -b $VOLTAPI_VOLTA_REPO_BRANCH $VOLTAPI_VOLTA_REPO $VOLTAPI_HTTPD_BASE_DIR
composer install
cp .env.example .env
php artisan key:generate

usermod -aG www-data $VOLTAPI_OS_USER
chown -R www-data:www-data "$VOLTAPI_HTTPD_BASE_DIR"
find "$VOLTAPI_HTTPD_BASE_DIR" -type d -exec chmod 2775 {} \;
find "$VOLTAPI_HTTPD_BASE_DIR" -type f -exec chmod 0664 {} \;

# Activate Volta on Nginx
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/volta /etc/nginx/sites-enabled/

# Add a welcome text upon terminal login
echo "source /home/$VOLTAPI_OS_USER/scripts/welcome" >> /home/$VOLTAPI_OS_USER/.bashrc

# Unpack root at the end, so files are modified before
unpack /filesystem/root /

# Cleanup
apt-get clean
apt-get autoremove -y